In [1]:
import numpy as np
import pressure_derivatives as pdev

In [2]:
np.polyval([0.0275, 3.7960, 86.6], 1.5)

92.355875

In [3]:
pdev.alpha_quartz()

(2.648,
 array([[ 86.6 ,   6.74,  12.4 ,  17.8 ,   0.  ,   0.  ],
        [  6.74,  86.6 ,  12.4 , -17.8 ,   0.  ,   0.  ],
        [ 12.4 ,  12.4 , 106.4 ,   0.  ,   0.  ,   0.  ],
        [ 17.8 , -17.8 ,   0.  ,  58.  ,   0.  ,   0.  ],
        [  0.  ,   0.  ,   0.  ,   0.  ,  58.  ,  17.8 ],
        [  0.  ,   0.  ,   0.  ,   0.  ,  17.8 ,  39.93]]))

In [4]:
pdev.alpha_quartz(1.5)

(2.744,
 array([[ 92.36,  16.93,  22.52,  12.04,   0.  ,   0.  ],
        [ 16.93,  92.36,  22.52, -12.04,   0.  ,   0.  ],
        [ 22.52,  22.52, 126.04,   0.  ,   0.  ,   0.  ],
        [ 12.04, -12.04,   0.  ,  61.58,   0.  ,   0.  ],
        [  0.  ,   0.  ,   0.  ,   0.  ,  61.58,  12.04],
        [  0.  ,   0.  ,   0.  ,   0.  ,  12.04,  37.71]]))

In [5]:
pdev.alpha_quartz(2.5)

(2.807,
 array([[ 96.26,  23.31,  28.72,   8.75,   0.  ,   0.  ],
        [ 23.31,  96.26,  28.72,  -8.75,   0.  ,   0.  ],
        [ 28.72,  28.72, 138.52,   0.  ,   0.  ,   0.  ],
        [  8.75,  -8.75,   0.  ,  63.08,   0.  ,   0.  ],
        [  0.  ,   0.  ,   0.  ,   0.  ,  63.08,   8.75],
        [  0.  ,   0.  ,   0.  ,   0.  ,   8.75,  36.48]]))

In [6]:
density, _ = pdev.alpha_quartz(2.5)
density

2.807