# Example of usage

This is a Jupyter notebook showing some of the functionality of the PyRockWave codes, including the use of its database. This is in intensive development (alpha state), so the code and functionality may be subject to major changes. That is why there are still no instructions on how to install it and no specific documentation on how to use it. However, the code is completely open source, so you can have fun with it at your own risk.

## Using the database

The code includes, among others, a (still incomplete) database of the elastic properties of common minerals. This database differs from other existing databases in that it is not a passive database, i.e. a set of text files containing data on elastic properties, but a file with functions that return the elastic properties of minerals under specific conditions and with which it has to interact. The idea is to provide an up-to-date, well-documented database of elastic properties with a rigorous tracking of changes (key for reproducibility).

The first action in a Jupyter notebook is to import the database as follows

In [1]:
import elastic_database as edb

If you then type ``edb.`` and press the TAB key, you will get a menu with all the options available in the database. For example, let's extract the properties of alpha quartz at a pressure of 1.8 GPa.

In [2]:
edb.alpha_quartz(1.8)

<class 'ElasticClass.ElasticProps'>

Mineral Name: Alpha_quartz
Reference Source: https://doi.org/10.1007/s00269-014-0711-z
Crystal System: Trigonal
Pressure (GPa): 1.8
Temperature (°C): 25
Density (g/cm3): 2.763

Stiffness Tensor (Cij) in GPa:
[[ 93.52  18.88  24.43  11.     0.     0.  ]
 [ 18.88  93.52  24.43 -11.     0.     0.  ]
 [ 24.43  24.43 129.83   0.     0.     0.  ]
 [ 11.   -11.     0.    62.1    0.     0.  ]
 [  0.     0.     0.     0.    62.1   11.  ]
 [  0.     0.     0.     0.    11.    37.32]]

Calculated average properties:
Bulk Modulus Voigt Average (GPa): 50.261
Bulk Modulus Reuss Average (GPa): 48.842
Bulk Modulus VRH Average (GPa): 49.551
Shear Modulus Voigt Average (GPa): 48.913
Shear Modulus Reuss Average (GPa): 44.236
Shear Modulus VRH Average (GPa): 46.575

Universal Elastic Anisotropy: 0.558
Kube's Anisotropy Index (proportional): 0.227

Isotropic Average Poisson Ratio: 0.142
Isotropic Average Vp (km/s): 6.357
Isotropic Average Vs (km/s): 4.106
Isotropic Aver

As you can see, the command returns a summary of the different properties of alpha quartz at 1.8 GPa pressure, including some average elastic properties of alpha quartz. If you want to access the function's own documentation you can use the ``help()`` or ``?`` command.

In [3]:
# alternatively you can use help(edb.alpha_quartz) or edb.alpha_quartz??
edb.alpha_quartz?

Signature: edb.alpha_quartz(P=1e-05)
Docstring:
Returns the corresponding elastic tensor (GPa) and density
(g/cm3) and other derived elastic properties of alpha quartz
as a function of pressure based on a polynomial fit from
experimental data of Wang et al. (2006) [1]

Caveats
-------
    - C44 elastic term is worse constrained than the others.
    The fitting has an R-squared value of 0.96
    - The function does not account for temperature effects
    and assumes room temperature.

Parameters
----------
P : numeric, optional
    Pressure in GPa. Default value is 1e-5 GPa (RT).

Returns
-------
properties : ElasticProps dataclass
    An object containing the following properties:
    - name: Name of the crystal ('alpha_quartz').
    - crystal_system: Crystal system.
    - temperature: Temperature in degrees Celsius (assumed 25).
    - pressure: Pressure in GPa.
    - density: Density in g/cm3.
    - cijs: 6x6 array representing the elastic tensor.
    - reference: Reference to the sou

Of course, you can store this information in a variable and access the different properties individually or in their entirety. For example:

In [4]:
quartz = edb.alpha_quartz(1.8)
quartz.Cij

array([[ 93.52,  18.88,  24.43,  11.  ,   0.  ,   0.  ],
       [ 18.88,  93.52,  24.43, -11.  ,   0.  ,   0.  ],
       [ 24.43,  24.43, 129.83,   0.  ,   0.  ,   0.  ],
       [ 11.  , -11.  ,   0.  ,  62.1 ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,  62.1 ,  11.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,  11.  ,  37.32]])

In [5]:
print(f'density = {quartz.density}')
print(f'Shear modulus (Hill average) = {quartz.G_hill}')

density = 2.763
Shear modulus (Hill average) = 46.574527852653404


Other random examples

In [6]:
# describe all the data
quartz

<class 'ElasticClass.ElasticProps'>

Mineral Name: Alpha_quartz
Reference Source: https://doi.org/10.1007/s00269-014-0711-z
Crystal System: Trigonal
Pressure (GPa): 1.8
Temperature (°C): 25
Density (g/cm3): 2.763

Stiffness Tensor (Cij) in GPa:
[[ 93.52  18.88  24.43  11.     0.     0.  ]
 [ 18.88  93.52  24.43 -11.     0.     0.  ]
 [ 24.43  24.43 129.83   0.     0.     0.  ]
 [ 11.   -11.     0.    62.1    0.     0.  ]
 [  0.     0.     0.     0.    62.1   11.  ]
 [  0.     0.     0.     0.    11.    37.32]]

Calculated average properties:
Bulk Modulus Voigt Average (GPa): 50.261
Bulk Modulus Reuss Average (GPa): 48.842
Bulk Modulus VRH Average (GPa): 49.551
Shear Modulus Voigt Average (GPa): 48.913
Shear Modulus Reuss Average (GPa): 44.236
Shear Modulus VRH Average (GPa): 46.575

Universal Elastic Anisotropy: 0.558
Kube's Anisotropy Index (proportional): 0.227

Isotropic Average Poisson Ratio: 0.142
Isotropic Average Vp (km/s): 6.357
Isotropic Average Vs (km/s): 4.106
Isotropic Aver

In [7]:
edb.omphacite(1.8)

<class 'ElasticClass.ElasticProps'>

Mineral Name: Omphacite
Reference Source: https://doi.org/10.1029/2018JB016964
Crystal System: Monoclinic
Pressure (GPa): 1.8
Temperature (°C): 25
Density (g/cm3): 3.388

Stiffness Tensor (Cij) in GPa:
[[245.8   92.34  81.79   0.     6.62   0.  ]
 [ 92.34 210.    64.46   0.     4.48   0.  ]
 [ 81.79  64.46 267.18   0.    36.     0.  ]
 [  0.     0.     0.    80.88   0.     6.3 ]
 [  6.62   4.48  36.     0.    70.57   0.  ]
 [  0.     0.     0.     6.3    0.    78.15]]

Calculated average properties:
Bulk Modulus Voigt Average (GPa): 133.351
Bulk Modulus Reuss Average (GPa): 128.763
Bulk Modulus VRH Average (GPa): 131.057
Shear Modulus Voigt Average (GPa): 78.213
Shear Modulus Reuss Average (GPa): 75.022
Shear Modulus VRH Average (GPa): 76.617

Universal Elastic Anisotropy: 0.248
Kube's Anisotropy Index (proportional): 0.099

Isotropic Average Poisson Ratio: 0.255
Isotropic Average Vp (km/s): 8.297
Isotropic Average Vs (km/s): 4.755
Isotropic Average

In [8]:
edb.diopside(1.8)

<class 'ElasticClass.ElasticProps'>

Mineral Name: Diopside
Reference Source: https://doi.org/10.1016/j.pepi.2013.12.011
Crystal System: Monoclinic
Pressure (GPa): 1.8
Temperature (°C): 25
Density (g/cm3): 3.313

Stiffness Tensor (Cij) in GPa:
[[240.6   86.27  77.58   0.     9.64   0.  ]
 [ 86.27 190.59  63.43   0.     3.98   0.  ]
 [ 77.58  63.43 257.9    0.    38.72   0.  ]
 [  0.     0.     0.    82.06   0.     4.09]
 [  9.64   3.98  38.72   0.    71.81   0.  ]
 [  0.     0.     0.     4.09   0.    81.56]]

Calculated average properties:
Bulk Modulus Voigt Average (GPa): 127.072
Bulk Modulus Reuss Average (GPa): 121.265
Bulk Modulus VRH Average (GPa): 124.168
Shear Modulus Voigt Average (GPa): 77.873
Shear Modulus Reuss Average (GPa): 74.297
Shear Modulus VRH Average (GPa): 76.085

Universal Elastic Anisotropy: 0.289
Kube's Anisotropy Index (proportional): 0.115

Isotropic Average Poisson Ratio: 0.246
Isotropic Average Vp (km/s): 8.252
Isotropic Average Vs (km/s): 4.792
Isotropic Av

In [9]:
edb.enstatite(1.8)

<class 'ElasticClass.ElasticProps'>

Mineral Name: Enstatite
Reference Source: https://doi.org/10.1002/2016GL069963
Crystal System: Orthorhombic
Pressure (GPa): 1.8
Temperature (°C): 25
Density (g/cm3): 3.337

Stiffness Tensor (Cij) in GPa:
[[252.37  90.97  74.92   0.     0.     0.  ]
 [ 90.97 192.45  67.71   0.     0.     0.  ]
 [ 74.92  67.71 244.64   0.     0.     0.  ]
 [  0.     0.     0.    86.8    0.     0.  ]
 [  0.     0.     0.     0.    81.35   0.  ]
 [  0.     0.     0.     0.     0.    84.81]]

Calculated average properties:
Bulk Modulus Voigt Average (GPa): 128.518
Bulk Modulus Reuss Average (GPa): 126.583
Bulk Modulus VRH Average (GPa): 127.550
Shear Modulus Voigt Average (GPa): 80.983
Shear Modulus Reuss Average (GPa): 79.543
Shear Modulus VRH Average (GPa): 80.263

Universal Elastic Anisotropy: 0.106
Kube's Anisotropy Index (proportional): 0.043

Isotropic Average Poisson Ratio: 0.240
Isotropic Average Vp (km/s): 8.384
Isotropic Average Vs (km/s): 4.904
Isotropic Avera

In [10]:
edb.forsterite_ZB2016(P=1.8)

<class 'ElasticClass.ElasticProps'>

Mineral Name: Forsterite
Reference Source: https://doi.org/10.1002/2016GL069949
Crystal System: Orthorhombic
Pressure (GPa): 1.8
Temperature (°C): 1027
Density (g/cm3): 3.285

Stiffness Tensor (Cij) in GPa:
[[282.82  72.83  67.77   0.     0.     0.  ]
 [ 72.83 183.61  71.08   0.     0.     0.  ]
 [ 67.77  71.08 208.99   0.     0.     0.  ]
 [  0.     0.     0.    57.3    0.     0.  ]
 [  0.     0.     0.     0.    69.17   0.  ]
 [  0.     0.     0.     0.     0.    68.96]]

Calculated average properties:
Bulk Modulus Voigt Average (GPa): 122.087
Bulk Modulus Reuss Average (GPa): 118.829
Bulk Modulus VRH Average (GPa): 120.458
Shear Modulus Voigt Average (GPa): 70.002
Shear Modulus Reuss Average (GPa): 67.842
Shear Modulus VRH Average (GPa): 68.922

Universal Elastic Anisotropy: 0.187
Kube's Anisotropy Index (proportional): 0.075

Isotropic Average Poisson Ratio: 0.260
Isotropic Average Vp (km/s): 8.040
Isotropic Average Vs (km/s): 4.580
Isotropic Av

In [11]:
edb.forsterite_Mao(P=1.8)

<class 'ElasticClass.ElasticProps'>

Mineral Name: Forsterite
Reference Source: https://doi.org/10.1016/j.epsl.2015.06.045
Crystal System: Orthorhombic
Pressure (GPa): 1.8
Temperature (°C): 627
Density (g/cm3): 3.301

Stiffness Tensor (Cij) in GPa:
[[310.33  53.85  67.18   0.     0.     0.  ]
 [ 53.85 189.12  78.3    0.     0.     0.  ]
 [ 67.18  78.3  220.88   0.     0.     0.  ]
 [  0.     0.     0.    60.23   0.     0.  ]
 [  0.     0.     0.     0.    74.11   0.  ]
 [  0.     0.     0.     0.     0.    73.78]]

Calculated average properties:
Bulk Modulus Voigt Average (GPa): 124.332
Bulk Modulus Reuss Average (GPa): 120.841
Bulk Modulus VRH Average (GPa): 122.586
Shear Modulus Voigt Average (GPa): 76.357
Shear Modulus Reuss Average (GPa): 72.656
Shear Modulus VRH Average (GPa): 74.507

Universal Elastic Anisotropy: 0.284
Kube's Anisotropy Index (proportional): 0.115

Isotropic Average Poisson Ratio: 0.247
Isotropic Average Vp (km/s): 8.199
Isotropic Average Vs (km/s): 4.751
Isotrop

In [12]:
edb.zoisite()

<class 'ElasticClass.ElasticProps'>

Mineral Name: Zoisite
Reference Source: https://doi.org/10.2138/am.2007.2329
Crystal System: Orthorhombic
Pressure (GPa): 0.0
Temperature (°C): 25
Density (g/cm3): 3.343

Stiffness Tensor (Cij) in GPa:
[[279.8  94.7  88.7   0.    0.    0. ]
 [ 94.7 249.2  27.5   0.    0.    0. ]
 [ 88.7  27.5 209.4   0.    0.    0. ]
 [  0.    0.    0.   51.8   0.    0. ]
 [  0.    0.    0.    0.   81.4   0. ]
 [  0.    0.    0.    0.    0.   66.3]]

Calculated average properties:
Bulk Modulus Voigt Average (GPa): 128.911
Bulk Modulus Reuss Average (GPa): 121.637
Bulk Modulus VRH Average (GPa): 125.274
Shear Modulus Voigt Average (GPa): 75.067
Shear Modulus Reuss Average (GPa): 70.643
Shear Modulus VRH Average (GPa): 72.855

Universal Elastic Anisotropy: 0.373
Kube's Anisotropy Index (proportional): 0.148

Isotropic Average Poisson Ratio: 0.256
Isotropic Average Vp (km/s): 8.157
Isotropic Average Vs (km/s): 4.668
Isotropic Average Vp/Vs: 1.747

In [13]:
edb.chlorite(1.8)

<class 'ElasticClass.ElasticProps'>

Mineral Name: Chlorite
Reference Source: https://doi.org/10.1002/2014GL059334
Crystal System: Monoclinic
Pressure (GPa): 1.8
Temperature (°C): 25
Density (g/cm3): 2.594

Stiffness Tensor (Cij) in GPa:
[[199.1   57.76  23.51   0.     3.55   0.  ]
 [ 57.76 201.96  31.01   0.     0.05   0.  ]
 [ 23.51  31.01 162.46   0.     0.78   0.  ]
 [  0.     0.     0.    24.55   0.     0.33]
 [  3.55   0.05   0.78   0.    23.81   0.  ]
 [  0.     0.     0.     0.33   0.    71.77]]

Calculated average properties:
Bulk Modulus Voigt Average (GPa): 87.564
Bulk Modulus Reuss Average (GPa): 85.220
Bulk Modulus VRH Average (GPa): 86.392
Shear Modulus Voigt Average (GPa): 54.109
Shear Modulus Reuss Average (GPa): 40.376
Shear Modulus VRH Average (GPa): 47.242

Universal Elastic Anisotropy: 1.728
Kube's Anisotropy Index (proportional): 0.655

Isotropic Average Poisson Ratio: 0.269
Isotropic Average Vp (km/s): 7.589
Isotropic Average Vs (km/s): 4.268
Isotropic Average Vp/

In [14]:
edb.pyrope(1.8)

<class 'ElasticClass.ElasticProps'>

Mineral Name: Pyrope
Reference Source: https://doi.org/10.1016/j.epsl.2012.11.041
Crystal System: Cubic
Pressure (GPa): 1.8
Temperature (°C): 750
Density (g/cm3): 3.740

Stiffness Tensor (Cij) in GPa:
[[284.1  107.2  107.2    0.     0.     0.  ]
 [107.2  284.1  107.2    0.     0.     0.  ]
 [107.2  107.2  284.1    0.     0.     0.  ]
 [  0.     0.     0.    90.26   0.     0.  ]
 [  0.     0.     0.     0.    90.26   0.  ]
 [  0.     0.     0.     0.     0.    90.26]]

Calculated average properties:
Bulk Modulus Voigt Average (GPa): 166.167
Bulk Modulus Reuss Average (GPa): 166.167
Bulk Modulus VRH Average (GPa): 166.167
Shear Modulus Voigt Average (GPa): 89.536
Shear Modulus Reuss Average (GPa): 89.527
Shear Modulus VRH Average (GPa): 89.532

Universal Elastic Anisotropy: 0.000
Kube's Anisotropy Index (proportional): 0.000

Isotropic Average Poisson Ratio: 0.272
Isotropic Average Vp (km/s): 8.738
Isotropic Average Vs (km/s): 4.893
Isotropic Average 

In [15]:
edb.plagioclase('An37')

<class 'ElasticClass.ElasticProps'>

Mineral Name: plagioclase_An37
Reference Source: https://doi.org/10.1002/2015JB012736
Crystal System: Triclinic
Pressure (GPa): 0.0
Temperature (°C): 25
Density (g/cm3): 2.666

Stiffness Tensor (Cij) in GPa:
[[ 96.2  46.1  38.4   5.9  -0.2  -0.4]
 [ 46.1 189.4  15.4  -7.   -5.1  -6.8]
 [ 38.4  15.4 171.9   2.2   7.2  -9.8]
 [  5.9  -7.    2.2  23.6  -1.1  -4.8]
 [ -0.2  -5.1   7.2  -1.1  33.1   1.4]
 [ -0.4  -6.8  -9.8  -4.8   1.4  35.5]]

Calculated average properties:
Bulk Modulus Voigt Average (GPa): 73.033
Bulk Modulus Reuss Average (GPa): 68.807
Bulk Modulus VRH Average (GPa): 70.920
Shear Modulus Voigt Average (GPa): 42.280
Shear Modulus Reuss Average (GPa): 33.539
Shear Modulus VRH Average (GPa): 37.910

Universal Elastic Anisotropy: 1.364
Kube's Anisotropy Index (proportional): 0.521

Isotropic Average Poisson Ratio: 0.273
Isotropic Average Vp (km/s): 6.750
Isotropic Average Vs (km/s): 3.771
Isotropic Average Vp/Vs: 1.790

In [16]:
edb.amphiboles('Pargasite')

<class 'ElasticClass.ElasticProps'>

Mineral Name: Pargasite
Reference Source: https://doi.org/10.1016/j.pepi.2016.10.010
Crystal System: Monoclinic
Pressure (GPa): 0.0
Temperature (°C): 25
Density (g/cm3): 3.163

Stiffness Tensor (Cij) in GPa:
[[141.6  57.1  49.6   0.   -0.2   0. ]
 [ 57.1 197.8  60.9   0.  -10.9   0. ]
 [ 49.6  60.9 225.4   0.  -31.4   0. ]
 [  0.    0.    0.   75.8   0.    3.3]
 [ -0.2 -10.9 -31.4   0.   49.9   0. ]
 [  0.    0.    0.    3.3   0.   51.7]]

Calculated average properties:
Bulk Modulus Voigt Average (GPa): 100.000
Bulk Modulus Reuss Average (GPa): 93.537
Bulk Modulus VRH Average (GPa): 96.768
Shear Modulus Voigt Average (GPa): 61.960
Shear Modulus Reuss Average (GPa): 57.112
Shear Modulus VRH Average (GPa): 59.536

Universal Elastic Anisotropy: 0.493
Kube's Anisotropy Index (proportional): 0.194

Isotropic Average Poisson Ratio: 0.245
Isotropic Average Vp (km/s): 7.463
Isotropic Average Vs (km/s): 4.338
Isotropic Average Vp/Vs: 1.720

In [17]:
edb.amphiboles?

Signature: edb.amphiboles(type='Hornblende')
Docstring:
Returns the corresponding elastic tensor (GPa) and density
(g/cm3) and other derived elastic properties of different
types of Ca-Na amphibole based on experimental data of
Brown and Abramson (2016) [1]

Caveats
-------
    - The function does not account for temperature or
    pressure effects and assumes room conditions

Parameters
----------
type : str
    the type of Ca-Na amphibole

Returns
-------
properties : ElasticProps dataclass
    An object containing the following properties:
    - name: Name of the crystal.
    - crystal_system: Crystal system.
    - temperature: Temperature in degrees Celsius (assumed 25).
    - pressure: Pressure in GPa.
    - density: Density in g/cm3.
    - cijs: 6x6 array representing the elastic tensor.
    - reference: Reference to the source publication.
    - Other average (seismic) properties

Examples
--------
>>> amph = amphiboles(type='Pargasite')

References
----------
[1] Brown, J.M., A

In [18]:
edb.antigorite()

<class 'ElasticClass.ElasticProps'>

Mineral Name: Antigorite
Reference Source: https://doi.org/10.1029/2022GL099411
Crystal System: Monoclinic
Pressure (GPa): 0.0
Temperature (°C): 25
Density (g/cm3): 2.615

Stiffness Tensor (Cij) in GPa:
[[190.6  61.3  21.3   0.    2.9   0. ]
 [ 61.3 208.2  19.    0.   -1.2   0. ]
 [ 21.3  19.   85.4   0.    0.4   0. ]
 [  0.    0.    0.   13.5   0.   -3.2]
 [  2.9  -1.2   0.4   0.   20.    0. ]
 [  0.    0.    0.   -3.2   0.   67.5]]

Calculated average properties:
Bulk Modulus Voigt Average (GPa): 76.378
Bulk Modulus Reuss Average (GPa): 61.104
Bulk Modulus VRH Average (GPa): 68.741
Shear Modulus Voigt Average (GPa): 45.707
Shear Modulus Reuss Average (GPa): 28.404
Shear Modulus VRH Average (GPa): 37.055

Universal Elastic Anisotropy: 3.296
Kube's Anisotropy Index (proportional): 1.087

Isotropic Average Poisson Ratio: 0.272
Isotropic Average Vp (km/s): 6.722
Isotropic Average Vs (km/s): 3.764
Isotropic Average Vp/Vs: 1.786

In [19]:
import sys
from datetime import date    
today = date.today().isoformat()

print(f'Notebook tested in {today} using:')
print('Python', sys.version)

Notebook tested in 2023-07-03 using:
Python 3.10.11 | packaged by Anaconda, Inc. | (main, Apr 20 2023, 18:56:50) [MSC v.1916 64 bit (AMD64)]
