In [1]:
import numpy as np
import database as db

In [2]:
np.polyval([0.0275, 3.7960, 86.6], 1.5)

92.355875

In [3]:
db.alpha_quartz(1.5)

<class 'ElasticClass.ElasticTensor'>

Mineral Name: alpha_quartz
Reference Source: https://doi.org/10.1007/s00269-014-0711-z
Crystal System: Trigonal
Pressure (GPa): 1.5
Temperature (°C): 25
Density (g/cm3): 2.744

Stiffness Tensor (Cij) in GPa:
[[ 92.36  16.93  22.52  12.04   0.     0.  ]
 [ 16.93  92.36  22.52 -12.04   0.     0.  ]
 [ 22.52  22.52 126.04   0.     0.     0.  ]
 [ 12.04 -12.04   0.    61.58   0.     0.  ]
 [  0.     0.     0.     0.    61.58  12.04]
 [  0.     0.     0.     0.    12.04  37.71]]

Calculated properties:
Bulk Modulus Voigt Average (GPa): 48.300
Bulk Modulus Reuss Average (GPa): 47.037
Bulk Modulus VRH Average (GPa): 47.668
Shear Modulus Voigt Average (GPa): 48.760
Shear Modulus Reuss Average (GPa): 43.893
Shear Modulus VRH Average (GPa): 46.326
Universal Elastic Anisotropy: 0.581
Isotropic Average Poisson Ratio: 0.133
Isotropic Average Vp (km/s): 6.315
Isotropic Average Vs (km/s): 4.109
Isotropic Average Vp/Vs: 1.537

In [4]:
quartz = db.alpha_quartz(1.8)
quartz.Cij

array([[ 93.52,  18.88,  24.43,  11.  ,   0.  ,   0.  ],
       [ 18.88,  93.52,  24.43, -11.  ,   0.  ,   0.  ],
       [ 24.43,  24.43, 129.83,   0.  ,   0.  ,   0.  ],
       [ 11.  , -11.  ,   0.  ,  62.1 ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,  62.1 ,  11.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,  11.  ,  37.32]])

In [5]:
quartz.density

2.763

In [6]:
db.alpha_quartz(2.5)

<class 'ElasticClass.ElasticTensor'>

Mineral Name: alpha_quartz
Reference Source: https://doi.org/10.1007/s00269-014-0711-z
Crystal System: Trigonal
Pressure (GPa): 2.5
Temperature (°C): 25
Density (g/cm3): 2.807

Stiffness Tensor (Cij) in GPa:
[[ 96.26  23.31  28.72   8.75   0.     0.  ]
 [ 23.31  96.26  28.72  -8.75   0.     0.  ]
 [ 28.72  28.72 138.52   0.     0.     0.  ]
 [  8.75  -8.75   0.    63.08   0.     0.  ]
 [  0.     0.     0.     0.    63.08   8.75]
 [  0.     0.     0.     0.     8.75  36.48]]

Calculated properties:
Bulk Modulus Voigt Average (GPa): 54.727
Bulk Modulus Reuss Average (GPa): 52.934
Bulk Modulus VRH Average (GPa): 53.830
Shear Modulus Voigt Average (GPa): 49.214
Shear Modulus Reuss Average (GPa): 44.831
Shear Modulus VRH Average (GPa): 47.022
Universal Elastic Anisotropy: 0.523
Isotropic Average Poisson Ratio: 0.162
Isotropic Average Vp (km/s): 6.443
Isotropic Average Vs (km/s): 4.093
Isotropic Average Vp/Vs: 1.574

In [7]:
db.omphacite(1.8)

<class 'ElasticClass.ElasticTensor'>

Mineral Name: omphacite
Reference Source: https://doi.org/10.1029/2018JB016964
Crystal System: Monoclinic
Pressure (GPa): 1.8
Temperature (°C): 25
Density (g/cm3): 3.388

Stiffness Tensor (Cij) in GPa:
[[245.8   92.34  81.79   0.     6.62   0.  ]
 [ 92.34 210.    64.46   0.     4.48   0.  ]
 [ 81.79  64.46 267.18   0.    36.     0.  ]
 [  0.     0.     0.    80.88   0.     6.3 ]
 [  6.62   4.48  36.     0.    70.57   0.  ]
 [  0.     0.     0.     6.3    0.    78.15]]

Calculated properties:
Bulk Modulus Voigt Average (GPa): 133.351
Bulk Modulus Reuss Average (GPa): 128.763
Bulk Modulus VRH Average (GPa): 131.057
Shear Modulus Voigt Average (GPa): 78.213
Shear Modulus Reuss Average (GPa): 75.022
Shear Modulus VRH Average (GPa): 76.617
Universal Elastic Anisotropy: 0.248
Isotropic Average Poisson Ratio: 0.255
Isotropic Average Vp (km/s): 8.297
Isotropic Average Vs (km/s): 4.755
Isotropic Average Vp/Vs: 1.745

In [8]:
db.diopside(1.8)

<class 'ElasticClass.ElasticTensor'>

Mineral Name: diopside
Reference Source: https://doi.org/10.1016/j.pepi.2013.12.011
Crystal System: Monoclinic
Pressure (GPa): 1.8
Temperature (°C): 25
Density (g/cm3): 3.313

Stiffness Tensor (Cij) in GPa:
[[240.6   86.27  77.58   0.     9.64   0.  ]
 [ 86.27 190.59  63.43   0.     3.98   0.  ]
 [ 77.58  63.43 257.9    0.    38.72   0.  ]
 [  0.     0.     0.    82.06   0.     4.09]
 [  9.64   3.98  38.72   0.    71.81   0.  ]
 [  0.     0.     0.     4.09   0.    81.56]]

Calculated properties:
Bulk Modulus Voigt Average (GPa): 127.072
Bulk Modulus Reuss Average (GPa): 121.265
Bulk Modulus VRH Average (GPa): 124.168
Shear Modulus Voigt Average (GPa): 77.873
Shear Modulus Reuss Average (GPa): 74.297
Shear Modulus VRH Average (GPa): 76.085
Universal Elastic Anisotropy: 0.289
Isotropic Average Poisson Ratio: 0.246
Isotropic Average Vp (km/s): 8.252
Isotropic Average Vs (km/s): 4.792
Isotropic Average Vp/Vs: 1.722

In [9]:
db.enstatite(1.8)

<class 'ElasticClass.ElasticTensor'>

Mineral Name: enstatite
Reference Source: https://doi.org/10.1002/2016GL069963
Crystal System: Orthorhombic
Pressure (GPa): 1.8
Temperature (°C): 25
Density (g/cm3): 3.337

Stiffness Tensor (Cij) in GPa:
[[252.37  90.97  74.92   0.     0.     0.  ]
 [ 90.97 192.45  67.71   0.     0.     0.  ]
 [ 74.92  67.71 244.64   0.     0.     0.  ]
 [  0.     0.     0.    86.8    0.     0.  ]
 [  0.     0.     0.     0.    81.35   0.  ]
 [  0.     0.     0.     0.     0.    84.81]]

Calculated properties:
Bulk Modulus Voigt Average (GPa): 128.518
Bulk Modulus Reuss Average (GPa): 126.583
Bulk Modulus VRH Average (GPa): 127.550
Shear Modulus Voigt Average (GPa): 80.983
Shear Modulus Reuss Average (GPa): 79.543
Shear Modulus VRH Average (GPa): 80.263
Universal Elastic Anisotropy: 0.106
Isotropic Average Poisson Ratio: 0.240
Isotropic Average Vp (km/s): 8.384
Isotropic Average Vs (km/s): 4.904
Isotropic Average Vp/Vs: 1.710

In [10]:
db.forsterite_ZB2016(P=1.8)

<class 'ElasticClass.ElasticTensor'>

Mineral Name: forsterite
Reference Source: https://doi.org/10.1002/2016GL069949
Crystal System: Orthorhombic
Pressure (GPa): 1.8
Temperature (°C): 1027
Density (g/cm3): 3.285

Stiffness Tensor (Cij) in GPa:
[[282.82  72.83  67.77   0.     0.     0.  ]
 [ 72.83 183.61  71.08   0.     0.     0.  ]
 [ 67.77  71.08 208.99   0.     0.     0.  ]
 [  0.     0.     0.    57.3    0.     0.  ]
 [  0.     0.     0.     0.    69.17   0.  ]
 [  0.     0.     0.     0.     0.    68.96]]

Calculated properties:
Bulk Modulus Voigt Average (GPa): 122.087
Bulk Modulus Reuss Average (GPa): 118.829
Bulk Modulus VRH Average (GPa): 120.458
Shear Modulus Voigt Average (GPa): 70.002
Shear Modulus Reuss Average (GPa): 67.842
Shear Modulus VRH Average (GPa): 68.922
Universal Elastic Anisotropy: 0.187
Isotropic Average Poisson Ratio: 0.260
Isotropic Average Vp (km/s): 8.040
Isotropic Average Vs (km/s): 4.580
Isotropic Average Vp/Vs: 1.755

In [11]:
db.zoisite()

<class 'ElasticClass.ElasticTensor'>

Mineral Name: zoisite
Reference Source: https://doi.org/10.2138/am.2007.2329
Crystal System: Orthorhombic
Pressure (GPa): 0.0
Temperature (°C): 25
Density (g/cm3): 3.343

Stiffness Tensor (Cij) in GPa:
[[279.8  94.7  88.7   0.    0.    0. ]
 [ 94.7 249.2  27.5   0.    0.    0. ]
 [ 88.7  27.5 209.4   0.    0.    0. ]
 [  0.    0.    0.   51.8   0.    0. ]
 [  0.    0.    0.    0.   81.4   0. ]
 [  0.    0.    0.    0.    0.   66.3]]

Calculated properties:
Bulk Modulus Voigt Average (GPa): 128.911
Bulk Modulus Reuss Average (GPa): 121.637
Bulk Modulus VRH Average (GPa): 125.274
Shear Modulus Voigt Average (GPa): 75.067
Shear Modulus Reuss Average (GPa): 70.643
Shear Modulus VRH Average (GPa): 72.855
Universal Elastic Anisotropy: 0.373
Isotropic Average Poisson Ratio: 0.256
Isotropic Average Vp (km/s): 8.157
Isotropic Average Vs (km/s): 4.668
Isotropic Average Vp/Vs: 1.747