In [1]:
import numpy as np
import database as db

In [2]:
np.polyval([0.0275, 3.7960, 86.6], 1.5)

92.355875

In [3]:
db.alpha_quartz(1.8)

<class 'ElasticClass.ElasticProps'>

Mineral Name: Alpha_quartz
Reference Source: https://doi.org/10.1007/s00269-014-0711-z
Crystal System: Trigonal
Pressure (GPa): 1.8
Temperature (°C): 25
Density (g/cm3): 2.763

Stiffness Tensor (Cij) in GPa:
[[ 93.52  18.88  24.43  11.     0.     0.  ]
 [ 18.88  93.52  24.43 -11.     0.     0.  ]
 [ 24.43  24.43 129.83   0.     0.     0.  ]
 [ 11.   -11.     0.    62.1    0.     0.  ]
 [  0.     0.     0.     0.    62.1   11.  ]
 [  0.     0.     0.     0.    11.    37.32]]

Calculated properties:
Bulk Modulus Voigt Average (GPa): 50.261
Bulk Modulus Reuss Average (GPa): 48.842
Bulk Modulus VRH Average (GPa): 49.551
Shear Modulus Voigt Average (GPa): 48.913
Shear Modulus Reuss Average (GPa): 44.236
Shear Modulus VRH Average (GPa): 46.575
Universal Elastic Anisotropy: 0.558
Isotropic Average Poisson Ratio: 0.142
Isotropic Average Vp (km/s): 6.357
Isotropic Average Vs (km/s): 4.106
Isotropic Average Vp/Vs: 1.548

In [4]:
quartz = db.alpha_quartz(1.8)
quartz.Cij

array([[ 93.52,  18.88,  24.43,  11.  ,   0.  ,   0.  ],
       [ 18.88,  93.52,  24.43, -11.  ,   0.  ,   0.  ],
       [ 24.43,  24.43, 129.83,   0.  ,   0.  ,   0.  ],
       [ 11.  , -11.  ,   0.  ,  62.1 ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,  62.1 ,  11.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,  11.  ,  37.32]])

In [5]:
quartz.density

2.763

In [6]:
db.alpha_quartz(2.5)

<class 'ElasticClass.ElasticProps'>

Mineral Name: Alpha_quartz
Reference Source: https://doi.org/10.1007/s00269-014-0711-z
Crystal System: Trigonal
Pressure (GPa): 2.5
Temperature (°C): 25
Density (g/cm3): 2.807

Stiffness Tensor (Cij) in GPa:
[[ 96.26  23.31  28.72   8.75   0.     0.  ]
 [ 23.31  96.26  28.72  -8.75   0.     0.  ]
 [ 28.72  28.72 138.52   0.     0.     0.  ]
 [  8.75  -8.75   0.    63.08   0.     0.  ]
 [  0.     0.     0.     0.    63.08   8.75]
 [  0.     0.     0.     0.     8.75  36.48]]

Calculated properties:
Bulk Modulus Voigt Average (GPa): 54.727
Bulk Modulus Reuss Average (GPa): 52.934
Bulk Modulus VRH Average (GPa): 53.830
Shear Modulus Voigt Average (GPa): 49.214
Shear Modulus Reuss Average (GPa): 44.831
Shear Modulus VRH Average (GPa): 47.022
Universal Elastic Anisotropy: 0.523
Isotropic Average Poisson Ratio: 0.162
Isotropic Average Vp (km/s): 6.443
Isotropic Average Vs (km/s): 4.093
Isotropic Average Vp/Vs: 1.574

In [7]:
db.omphacite(1.8)

<class 'ElasticClass.ElasticProps'>

Mineral Name: Omphacite
Reference Source: https://doi.org/10.1029/2018JB016964
Crystal System: Monoclinic
Pressure (GPa): 1.8
Temperature (°C): 25
Density (g/cm3): 3.388

Stiffness Tensor (Cij) in GPa:
[[245.8   92.34  81.79   0.     6.62   0.  ]
 [ 92.34 210.    64.46   0.     4.48   0.  ]
 [ 81.79  64.46 267.18   0.    36.     0.  ]
 [  0.     0.     0.    80.88   0.     6.3 ]
 [  6.62   4.48  36.     0.    70.57   0.  ]
 [  0.     0.     0.     6.3    0.    78.15]]

Calculated properties:
Bulk Modulus Voigt Average (GPa): 133.351
Bulk Modulus Reuss Average (GPa): 128.763
Bulk Modulus VRH Average (GPa): 131.057
Shear Modulus Voigt Average (GPa): 78.213
Shear Modulus Reuss Average (GPa): 75.022
Shear Modulus VRH Average (GPa): 76.617
Universal Elastic Anisotropy: 0.248
Isotropic Average Poisson Ratio: 0.255
Isotropic Average Vp (km/s): 8.297
Isotropic Average Vs (km/s): 4.755
Isotropic Average Vp/Vs: 1.745

In [8]:
db.diopside(1.8)

<class 'ElasticClass.ElasticProps'>

Mineral Name: Diopside
Reference Source: https://doi.org/10.1016/j.pepi.2013.12.011
Crystal System: Monoclinic
Pressure (GPa): 1.8
Temperature (°C): 25
Density (g/cm3): 3.313

Stiffness Tensor (Cij) in GPa:
[[240.6   86.27  77.58   0.     9.64   0.  ]
 [ 86.27 190.59  63.43   0.     3.98   0.  ]
 [ 77.58  63.43 257.9    0.    38.72   0.  ]
 [  0.     0.     0.    82.06   0.     4.09]
 [  9.64   3.98  38.72   0.    71.81   0.  ]
 [  0.     0.     0.     4.09   0.    81.56]]

Calculated properties:
Bulk Modulus Voigt Average (GPa): 127.072
Bulk Modulus Reuss Average (GPa): 121.265
Bulk Modulus VRH Average (GPa): 124.168
Shear Modulus Voigt Average (GPa): 77.873
Shear Modulus Reuss Average (GPa): 74.297
Shear Modulus VRH Average (GPa): 76.085
Universal Elastic Anisotropy: 0.289
Isotropic Average Poisson Ratio: 0.246
Isotropic Average Vp (km/s): 8.252
Isotropic Average Vs (km/s): 4.792
Isotropic Average Vp/Vs: 1.722

In [9]:
db.enstatite(1.8)

<class 'ElasticClass.ElasticProps'>

Mineral Name: Enstatite
Reference Source: https://doi.org/10.1002/2016GL069963
Crystal System: Orthorhombic
Pressure (GPa): 1.8
Temperature (°C): 25
Density (g/cm3): 3.337

Stiffness Tensor (Cij) in GPa:
[[252.37  90.97  74.92   0.     0.     0.  ]
 [ 90.97 192.45  67.71   0.     0.     0.  ]
 [ 74.92  67.71 244.64   0.     0.     0.  ]
 [  0.     0.     0.    86.8    0.     0.  ]
 [  0.     0.     0.     0.    81.35   0.  ]
 [  0.     0.     0.     0.     0.    84.81]]

Calculated properties:
Bulk Modulus Voigt Average (GPa): 128.518
Bulk Modulus Reuss Average (GPa): 126.583
Bulk Modulus VRH Average (GPa): 127.550
Shear Modulus Voigt Average (GPa): 80.983
Shear Modulus Reuss Average (GPa): 79.543
Shear Modulus VRH Average (GPa): 80.263
Universal Elastic Anisotropy: 0.106
Isotropic Average Poisson Ratio: 0.240
Isotropic Average Vp (km/s): 8.384
Isotropic Average Vs (km/s): 4.904
Isotropic Average Vp/Vs: 1.710

In [10]:
db.forsterite_ZB2016(P=1.8)

<class 'ElasticClass.ElasticProps'>

Mineral Name: Forsterite
Reference Source: https://doi.org/10.1002/2016GL069949
Crystal System: Orthorhombic
Pressure (GPa): 1.8
Temperature (°C): 1027
Density (g/cm3): 3.285

Stiffness Tensor (Cij) in GPa:
[[282.82  72.83  67.77   0.     0.     0.  ]
 [ 72.83 183.61  71.08   0.     0.     0.  ]
 [ 67.77  71.08 208.99   0.     0.     0.  ]
 [  0.     0.     0.    57.3    0.     0.  ]
 [  0.     0.     0.     0.    69.17   0.  ]
 [  0.     0.     0.     0.     0.    68.96]]

Calculated properties:
Bulk Modulus Voigt Average (GPa): 122.087
Bulk Modulus Reuss Average (GPa): 118.829
Bulk Modulus VRH Average (GPa): 120.458
Shear Modulus Voigt Average (GPa): 70.002
Shear Modulus Reuss Average (GPa): 67.842
Shear Modulus VRH Average (GPa): 68.922
Universal Elastic Anisotropy: 0.187
Isotropic Average Poisson Ratio: 0.260
Isotropic Average Vp (km/s): 8.040
Isotropic Average Vs (km/s): 4.580
Isotropic Average Vp/Vs: 1.755

In [11]:
db.zoisite()

<class 'ElasticClass.ElasticProps'>

Mineral Name: Zoisite
Reference Source: https://doi.org/10.2138/am.2007.2329
Crystal System: Orthorhombic
Pressure (GPa): 0.0
Temperature (°C): 25
Density (g/cm3): 3.343

Stiffness Tensor (Cij) in GPa:
[[279.8  94.7  88.7   0.    0.    0. ]
 [ 94.7 249.2  27.5   0.    0.    0. ]
 [ 88.7  27.5 209.4   0.    0.    0. ]
 [  0.    0.    0.   51.8   0.    0. ]
 [  0.    0.    0.    0.   81.4   0. ]
 [  0.    0.    0.    0.    0.   66.3]]

Calculated properties:
Bulk Modulus Voigt Average (GPa): 128.911
Bulk Modulus Reuss Average (GPa): 121.637
Bulk Modulus VRH Average (GPa): 125.274
Shear Modulus Voigt Average (GPa): 75.067
Shear Modulus Reuss Average (GPa): 70.643
Shear Modulus VRH Average (GPa): 72.855
Universal Elastic Anisotropy: 0.373
Isotropic Average Poisson Ratio: 0.256
Isotropic Average Vp (km/s): 8.157
Isotropic Average Vs (km/s): 4.668
Isotropic Average Vp/Vs: 1.747

In [12]:
db.chlorite(1.8)

<class 'ElasticClass.ElasticProps'>

Mineral Name: Chlorite
Reference Source: https://doi.org/10.1002/2014GL059334
Crystal System: Monoclinic
Pressure (GPa): 1.8
Temperature (°C): 25
Density (g/cm3): 2.594

Stiffness Tensor (Cij) in GPa:
[[199.1   57.76  23.51   0.     3.55   0.  ]
 [ 57.76 201.96  31.01   0.     0.05   0.  ]
 [ 23.51  31.01 162.46   0.     0.78   0.  ]
 [  0.     0.     0.    24.55   0.     0.33]
 [  3.55   0.05   0.78   0.    23.81   0.  ]
 [  0.     0.     0.     0.33   0.    71.77]]

Calculated properties:
Bulk Modulus Voigt Average (GPa): 87.564
Bulk Modulus Reuss Average (GPa): 85.220
Bulk Modulus VRH Average (GPa): 86.392
Shear Modulus Voigt Average (GPa): 54.109
Shear Modulus Reuss Average (GPa): 40.376
Shear Modulus VRH Average (GPa): 47.242
Universal Elastic Anisotropy: 1.728
Isotropic Average Poisson Ratio: 0.269
Isotropic Average Vp (km/s): 7.589
Isotropic Average Vs (km/s): 4.268
Isotropic Average Vp/Vs: 1.778

In [13]:
db.pyrope(1.8)

<class 'ElasticClass.ElasticProps'>

Mineral Name: Pyrope
Reference Source: https://doi.org/10.1016/j.epsl.2012.11.041
Crystal System: Cubic
Pressure (GPa): 1.8
Temperature (°C): 750
Density (g/cm3): 3.740

Stiffness Tensor (Cij) in GPa:
[[284.1  107.2  107.2    0.     0.     0.  ]
 [107.2  284.1  107.2    0.     0.     0.  ]
 [107.2  107.2  284.1    0.     0.     0.  ]
 [  0.     0.     0.    90.26   0.     0.  ]
 [  0.     0.     0.     0.    90.26   0.  ]
 [  0.     0.     0.     0.     0.    90.26]]

Calculated properties:
Bulk Modulus Voigt Average (GPa): 166.167
Bulk Modulus Reuss Average (GPa): 166.167
Bulk Modulus VRH Average (GPa): 166.167
Shear Modulus Voigt Average (GPa): 89.536
Shear Modulus Reuss Average (GPa): 89.527
Shear Modulus VRH Average (GPa): 89.532
Universal Elastic Anisotropy: 0.000
Isotropic Average Poisson Ratio: 0.272
Isotropic Average Vp (km/s): 8.738
Isotropic Average Vs (km/s): 4.893
Isotropic Average Vp/Vs: 1.786

In [14]:
db.plagioclase('An37')

<class 'ElasticClass.ElasticProps'>

Mineral Name: plagioclase_An37
Reference Source: https://doi.org/10.1002/2015JB012736
Crystal System: Triclinic
Pressure (GPa): 0.0
Temperature (°C): 25
Density (g/cm3): 2.666

Stiffness Tensor (Cij) in GPa:
[[ 96.2  46.1  38.4   5.9  -0.2  -0.4]
 [ 46.1 189.4  15.4  -7.   -5.1  -6.8]
 [ 38.4  15.4 171.9   2.2   7.2  -9.8]
 [  5.9  -7.    2.2  23.6  -1.1  -4.8]
 [ -0.2  -5.1   7.2  -1.1  33.1   1.4]
 [ -0.4  -6.8  -9.8  -4.8   1.4  35.5]]

Calculated properties:
Bulk Modulus Voigt Average (GPa): 73.033
Bulk Modulus Reuss Average (GPa): 68.807
Bulk Modulus VRH Average (GPa): 70.920
Shear Modulus Voigt Average (GPa): 42.280
Shear Modulus Reuss Average (GPa): 33.539
Shear Modulus VRH Average (GPa): 37.910
Universal Elastic Anisotropy: 1.364
Isotropic Average Poisson Ratio: 0.273
Isotropic Average Vp (km/s): 6.750
Isotropic Average Vs (km/s): 3.771
Isotropic Average Vp/Vs: 1.790

In [15]:
db.amphiboles('Pargasite')

<class 'ElasticClass.ElasticProps'>

Mineral Name: Pargasite
Reference Source: https://doi.org/10.1016/j.pepi.2016.10.010
Crystal System: Monoclinic
Pressure (GPa): 0.0
Temperature (°C): 25
Density (g/cm3): 3.163

Stiffness Tensor (Cij) in GPa:
[[141.6  57.1  49.6   0.   -0.2   0. ]
 [ 57.1 197.8  60.9   0.  -10.9   0. ]
 [ 49.6  60.9 225.4   0.  -31.4   0. ]
 [  0.    0.    0.   75.8   0.    3.3]
 [ -0.2 -10.9 -31.4   0.   49.9   0. ]
 [  0.    0.    0.    3.3   0.   51.7]]

Calculated properties:
Bulk Modulus Voigt Average (GPa): 100.000
Bulk Modulus Reuss Average (GPa): 93.537
Bulk Modulus VRH Average (GPa): 96.768
Shear Modulus Voigt Average (GPa): 61.960
Shear Modulus Reuss Average (GPa): 57.112
Shear Modulus VRH Average (GPa): 59.536
Universal Elastic Anisotropy: 0.493
Isotropic Average Poisson Ratio: 0.245
Isotropic Average Vp (km/s): 7.463
Isotropic Average Vs (km/s): 4.338
Isotropic Average Vp/Vs: 1.720

In [16]:
import sys
from datetime import date    
today = date.today().isoformat()

print(f'Notebook tested in {today} using:')
print('Python', sys.version)
print('Numpy', np.__version__)

Notebook tested in 2023-06-12 using:
Python 3.10.11 | packaged by Anaconda, Inc. | (main, Apr 20 2023, 18:56:50) [MSC v.1916 64 bit (AMD64)]
Numpy 1.24.3
