# Demonstration of the functionality of the ``christoffel`` module

TODO

In [1]:
# import some general scientific Python libraries
import numpy as np

# import required PyRockWave modules
import christoffel as ch

In [2]:
# load test data
Cij = np.array([[118.8,  53.8,  53.8,   0. ,   0. ,   0. ],
                [ 53.8, 118.8,  53.8,   0. ,   0. ,   0. ],
                [ 53.8,  53.8, 118.8,   0. ,   0. ,   0. ],
                [  0. ,   0. ,   0. ,  59.4,   0. ,   0. ],
                [  0. ,   0. ,   0. ,   0. ,  59.4,   0. ],
                [  0. ,   0. ,   0. ,   0. ,   0. ,  59.4]])

density = 5.307

In [3]:
scaling_factor = 1 / density

In [4]:
Cijkl = ch._rearrange_tensor(Cij)
Cijkl.shape

(3, 3, 3, 3)

In [5]:
Mij = ch._christoffel_matrix(wavevector=np.array([1,0,0]), Cijkl=Cijkl)
Mij = Mij * scaling_factor
Mij

array([[22.38552855,  0.        ,  0.        ],
       [ 0.        , 11.19276427,  0.        ],
       [ 0.        ,  0.        , 11.19276427]])

In [6]:
eigenvalues, eigenvectors = ch._calc_eigen(Mij)  # eigenvalues (3,), eigenvectors (3,3)

In [7]:
ch.calc_phase_velocities(eigenvalues)  # (Vs2, Vs1, Vp)

array([3.34555889, 3.34555889, 4.73133475])

Test another direction, e.g. [1,1,0]

In [8]:
M2 = ch._christoffel_matrix(wavevector=np.array([1,1,0]), Cijkl=Cijkl)
M2 = M2 * scaling_factor
eigenvalues, eigenvectors = ch._calc_eigen(M2)

ch.calc_phase_velocities(eigenvalues)  # (Vs2, Vs1, Vp)

array([2.47466911, 3.34555889, 5.23968564])

In [9]:
import sys
from datetime import date    
today = date.today().isoformat()

print(f'Notebook tested in {today} using:')
print('Python', sys.version)
print('Numpy', np.__version__)

Notebook tested in 2023-07-27 using:
Python 3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:09:20) [MSC v.1916 64 bit (AMD64)]
Numpy 1.25.0
