In [1]:
# import some some Python scientific libraries 
import numpy as np
np.set_printoptions(suppress=True)

# import the database
import elastic_database as db

Mineral Elastic Database v.2024.2.01 imported


In [2]:
%run layered_media.py

In [3]:
fo = db.forsterite_Mao(P=1.8)
pl = db.plagioclase('An37')

In [4]:
fo.Cij

array([[310.33,  53.85,  67.18,   0.  ,   0.  ,   0.  ],
       [ 53.85, 189.12,  78.3 ,   0.  ,   0.  ,   0.  ],
       [ 67.18,  78.3 , 220.88,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,  60.23,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,  74.11,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,  73.78]])

In [5]:
pl.Cij

array([[ 96.2,  46.1,  38.4,   5.9,  -0.2,  -0.4],
       [ 46.1, 189.4,  15.4,  -7. ,  -5.1,  -6.8],
       [ 38.4,  15.4, 171.9,   2.2,   7.2,  -9.8],
       [  5.9,  -7. ,   2.2,  23.6,  -1.1,  -4.8],
       [ -0.2,  -5.1,   7.2,  -1.1,  33.1,   1.4],
       [ -0.4,  -6.8,  -9.8,  -4.8,   1.4,  35.5]])

In [6]:
v1 = 0.45
v2 = 0.55

In [7]:
eff_c, eff_s, eff_c_frm_s = schoenberg_muir_layered_medium(fo.Cij, pl.Cij, v1, v2)
print("Effective stiffness matrix:\n", np.around(eff_c, 3))
print("")
print("Effective compliance matrix:\n", np.around(eff_s, 4))
print("")
print("Effective stiffness from compliance matrix:\n", np.around(eff_c_frm_s, 3))

Effective stiffness matrix:
 [[191.32   47.569  49.501   4.579   0.249  -0.411]
 [ 47.569 184.02   40.111  -5.093  -3.045  -4.659]
 [ 49.501  40.111 190.634   1.907   5.885  -5.976]
 [  4.579  -5.093   1.907  32.47   -1.147  -3.588]
 [  0.249  -3.045   5.885  -1.147  43.948   1.103]
 [ -0.411  -4.659  -5.976  -3.588   1.103  52.469]]

Effective compliance matrix:
 [[ 0.0059 -0.0013 -0.0012 -0.0018  0.0001 -0.0003]
 [-0.0013  0.006  -0.0003  0.0023  0.001   0.0005]
 [-0.0012 -0.0003  0.0058 -0.0003 -0.0009  0.0011]
 [-0.0018  0.0023 -0.0003  0.0314  0.0009  0.004 ]
 [ 0.0001  0.001  -0.0009  0.0009  0.0229 -0.0009]
 [-0.0003  0.0005  0.0011  0.004  -0.0009  0.0193]]

Effective stiffness from compliance matrix:
 [[189.213  39.426  41.668   8.674  -1.075  -2.491]
 [ 39.426 180.409  16.385 -10.104  -7.385  -3.183]
 [ 41.668  16.385 184.318   4.076   5.505 -10.951]
 [  8.674 -10.104   4.076  34.001  -0.991  -6.938]
 [ -1.075  -7.385   5.505  -0.991  44.242   2.01 ]
 [ -2.491  -3.183 -10.951

In [8]:
np.around(np.linalg.inv(eff_c), 3)

array([[ 0.006, -0.001, -0.001, -0.001,  0.   , -0.   ],
       [-0.001,  0.006, -0.001,  0.001,  0.001,  0.   ],
       [-0.001, -0.001,  0.006, -0.   , -0.001,  0.001],
       [-0.001,  0.001, -0.   ,  0.031,  0.001,  0.002],
       [ 0.   ,  0.001, -0.001,  0.001,  0.023, -0.   ],
       [-0.   ,  0.   ,  0.001,  0.002, -0.   ,  0.019]])

---

In [9]:
pl.Cij

array([[ 96.2,  46.1,  38.4,   5.9,  -0.2,  -0.4],
       [ 46.1, 189.4,  15.4,  -7. ,  -5.1,  -6.8],
       [ 38.4,  15.4, 171.9,   2.2,   7.2,  -9.8],
       [  5.9,  -7. ,   2.2,  23.6,  -1.1,  -4.8],
       [ -0.2,  -5.1,   7.2,  -1.1,  33.1,   1.4],
       [ -0.4,  -6.8,  -9.8,  -4.8,   1.4,  35.5]])

In [10]:
# Cnn
pl.Cij[2:5, 2:5]

array([[171.9,   2.2,   7.2],
       [  2.2,  23.6,  -1.1],
       [  7.2,  -1.1,  33.1]])

In [11]:
# Ctn
pl.Cij[[0,1,5], 2:5]

array([[38.4,  5.9, -0.2],
       [15.4, -7. , -5.1],
       [-9.8, -4.8,  1.4]])

In [12]:
# Ctt
pl.Cij[[0,1,5], 0:3]

array([[ 96.2,  46.1,  38.4],
       [ 46.1, 189.4,  15.4],
       [ -0.4,  -6.8,  -9.8]])

In [13]:
np.array([[pl.Cij[0,0], pl.Cij[0,1], pl.Cij[0,5]], [pl.Cij[0,1], pl.Cij[1,1], pl.Cij[1,5]], [pl.Cij[0,5], pl.Cij[1,5], pl.Cij[5,5]]])

array([[ 96.2,  46.1,  -0.4],
       [ 46.1, 189.4,  -6.8],
       [ -0.4,  -6.8,  35.5]])

In [14]:
row_indices = np.array([0, 0, 0, 0, 1, 1, 0, 1, 5])
col_indices = np.array([0, 1, 5, 1, 1, 5, 5, 5, 5])

pl.Cij[row_indices, col_indices].reshape(3, 3)

array([[ 96.2,  46.1,  -0.4],
       [ 46.1, 189.4,  -6.8],
       [ -0.4,  -6.8,  35.5]])

In [15]:
row_indices = [0, 1, 5]
col_indices = [0, 1, 5]

pl.Cij[np.ix_(row_indices, col_indices)]

array([[ 96.2,  46.1,  -0.4],
       [ 46.1, 189.4,  -6.8],
       [ -0.4,  -6.8,  35.5]])

---

In [16]:
Cnn = np.array([[190.6342, 1.9067, 5.8847],
                [  1.9067, 32.4701, -1.1466],
                [  5.8847, -1.1466, 43.948 ]])

Ctn = np.array([[49.5007, 4.5791, 0.249 ],
                [40.1111, -5.093, -3.0449],
                [-5.9755, -3.5877, 1.1028]])

Ctt = np.array([[191.3203, 47.5692, -0.4109],
                [ 47.5692, 184.0196, -4.6592],
                [ -0.4109, -4.6592, 52.4687]])

In [17]:
 # Assemble the effective stiffness matrix
effective_stiffness = np.zeros((6, 6))
effective_stiffness[:3, :3] = Ctt[:3, :3]
effective_stiffness[3:, 3:] = Cnn[:3, :3]
effective_stiffness[:3, 3:] = Ctn[:3, :3].T
effective_stiffness[3:, :3] = Ctn[:3, :3]

effective_stiffness

array([[191.3203,  47.5692,  -0.4109,  49.5007,  40.1111,  -5.9755],
       [ 47.5692, 184.0196,  -4.6592,   4.5791,  -5.093 ,  -3.5877],
       [ -0.4109,  -4.6592,  52.4687,   0.249 ,  -3.0449,   1.1028],
       [ 49.5007,   4.5791,   0.249 , 190.6342,   1.9067,   5.8847],
       [ 40.1111,  -5.093 ,  -3.0449,   1.9067,  32.4701,  -1.1466],
       [ -5.9755,  -3.5877,   1.1028,   5.8847,  -1.1466,  43.948 ]])

In [18]:
np.block([
        [Ctt, Ctn],
        [Ctn.T, Cnn]
    ])

array([[191.3203,  47.5692,  -0.4109,  49.5007,   4.5791,   0.249 ],
       [ 47.5692, 184.0196,  -4.6592,  40.1111,  -5.093 ,  -3.0449],
       [ -0.4109,  -4.6592,  52.4687,  -5.9755,  -3.5877,   1.1028],
       [ 49.5007,  40.1111,  -5.9755, 190.6342,   1.9067,   5.8847],
       [  4.5791,  -5.093 ,  -3.5877,   1.9067,  32.4701,  -1.1466],
       [  0.249 ,  -3.0449,   1.1028,   5.8847,  -1.1466,  43.948 ]])

In [19]:
# Effective stiffness tensor in full Voigt notation
eff_c = np.zeros((6, 6))
eff_c[0, 0] = Ctt[0, 0]
eff_c[0, 1] = Ctt[0, 1]
eff_c[0, 2] = Ctn[0, 0]
eff_c[0, 3] = Ctn[0, 1]
eff_c[0, 4] = Ctn[0, 2]
eff_c[0, 5] = Ctt[0, 2]
eff_c[1, :] = eff_c[0, :]  # Due to symmetry
eff_c[2, 0] = Ctn[0, 0]
eff_c[2, 1] = Ctn[1, 1]
eff_c[2, 2] = Cnn[0, 0]
eff_c[2, 3] = Cnn[0, 1]
eff_c[2, 4] = Cnn[0, 2]
eff_c[2, 5] = Ctn[1, 2]
eff_c[3:, :] = eff_c[:, 3:].T  # Due to symmetry
eff_c[5, 5] = Ctt[2, 2]

eff_c

array([[191.3203,  47.5692,  49.5007,   4.5791,   0.249 ,  -0.4109],
       [191.3203,  47.5692,  49.5007,   4.5791,   0.249 ,  -0.4109],
       [ 49.5007,  -5.093 , 190.6342,   1.9067,   5.8847,  -3.0449],
       [  4.5791,   4.5791,   1.9067,   0.    ,   0.    ,   0.    ],
       [  0.249 ,   0.249 ,   5.8847,   0.    ,   0.    ,   0.    ],
       [ -0.4109,  -0.4109,  -3.0449,   0.    ,   0.    ,  52.4687]])

In [20]:
eff_c = np.array(
    [
        [Ctt[0, 0], Ctt[0, 1], Ctn[0, 0], Ctn[0, 1], Ctn[0, 2], Ctt[0, 2]],
        [Ctt[1, 0], Ctt[1, 1], Ctn[1, 0], Ctn[1, 1], Ctn[1, 2], Ctt[1, 2]],
        [Ctn[0, 0], Ctn[1, 0], Cnn[0, 0], Cnn[1, 0], Cnn[0, 2], Ctn[2, 0]],
        [Ctn[0, 1], Ctn[1, 1], Cnn[1, 0], Cnn[1, 1], Cnn[1, 2], Ctn[2, 1]],
        [Ctn[0, 2], Ctn[1, 2], Cnn[0, 2], Cnn[1, 2], Cnn[2, 2], Ctn[2, 2]],
        [Ctt[0, 2], Ctt[1, 2], Ctn[2, 0], Ctn[2, 1], Ctn[2, 2], Ctt[2, 2]],
    ]
)

eff_c


array([[191.3203,  47.5692,  49.5007,   4.5791,   0.249 ,  -0.4109],
       [ 47.5692, 184.0196,  40.1111,  -5.093 ,  -3.0449,  -4.6592],
       [ 49.5007,  40.1111, 190.6342,   1.9067,   5.8847,  -5.9755],
       [  4.5791,  -5.093 ,   1.9067,  32.4701,  -1.1466,  -3.5877],
       [  0.249 ,  -3.0449,   5.8847,  -1.1466,  43.948 ,   1.1028],
       [ -0.4109,  -4.6592,  -5.9755,  -3.5877,   1.1028,  52.4687]])

In [21]:
# Effective stiffness tensor in full Voigt notation
eff_c = np.zeros((6, 6))
eff_c[0, 0] = Ctt[0, 0]
eff_c[1, 1] = Ctt[1, 1]
eff_c[2, 2] = Cnn[0, 0]
eff_c[3, 3] = Cnn[1, 1]
eff_c[4, 4] = Cnn[2, 2]
eff_c[5, 5] = Ctt[2, 2]

eff_c[0, 1] = Ctt[0,1]
eff_c[0, 2] = Ctn[0,0]
eff_c[0, 3] = Ctn[0,1]
eff_c[0, 4] = Ctn[0,2]
eff_c[0, 5] = Ctt[0,2]
eff_c[1, 2] = Ctn[1,0]
eff_c[1, 3] = Ctn[1,1]
eff_c[1, 4] = Ctn[1,2]
eff_c[1, 5] = Ctt[1,2]
eff_c[2, 3] = Cnn[1,0]
eff_c[2, 4] = Cnn[0,2]
eff_c[2, 5] = Ctn[2,0]
eff_c[3, 4] = Cnn[1,2]
eff_c[3, 5] = Ctn[2,1]
eff_c[4, 5] = Ctn[2,2]

# Symmetrize the tensor
eff_c2 = eff_c.copy()
np.fill_diagonal(eff_c2, 0)
eff_c = eff_c + eff_c2.T

eff_c

array([[191.3203,  47.5692,  49.5007,   4.5791,   0.249 ,  -0.4109],
       [ 47.5692, 184.0196,  40.1111,  -5.093 ,  -3.0449,  -4.6592],
       [ 49.5007,  40.1111, 190.6342,   1.9067,   5.8847,  -5.9755],
       [  4.5791,  -5.093 ,   1.9067,  32.4701,  -1.1466,  -3.5877],
       [  0.249 ,  -3.0449,   5.8847,  -1.1466,  43.948 ,   1.1028],
       [ -0.4109,  -4.6592,  -5.9755,  -3.5877,   1.1028,  52.4687]])