Any triclinic vector X in a given 3-D cartesian coordinate system can be decomposed by a cascade of projections into a sum of vectors belonging to the different symmetry classes: $X = X_{tric} + X_{mon} + X_{ort} + X_{tet} + X_{hex} + X_{iso}$.

In [1]:
import numpy as np
from decompose import *

In [2]:
# Elastic stiffness tensor of Olivine used in Browaeys and Chevrot (2004)
Cij = np.array(
    [[192,  66,  60, 0.0, 0.0, 0.0],
    [  66, 160,  56, 0.0, 0.0, 0.0],
    [  60,  56, 272, 0.0, 0.0, 0.0],
    [ 0.0, 0.0, 0.0,  60, 0.0, 0.0],
    [ 0.0, 0.0, 0.0, 0.0,  62, 0.0],
    [ 0.0, 0.0, 0.0, 0.0, 0.0,  49]])

In [3]:
X_tot = tensor_to_vector(Cij)
X_tot

array([192.        , 160.        , 272.        ,  79.19595949,
        84.85281374,  93.33809512, 120.        , 124.        ,
        98.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ])

In [4]:
olivine = decompose_Cij(Cij)

In [5]:
olivine

{'isotropic': array([[194.66666667,  67.33333333,  67.33333333,   0.        ,
           0.        ,   0.        ],
        [ 67.33333333, 194.66666667,  67.33333333,   0.        ,
           0.        ,   0.        ],
        [ 67.33333333,  67.33333333, 194.66666667,   0.        ,
           0.        ,   0.        ],
        [  0.        ,   0.        ,   0.        ,  63.66666667,
           0.        ,   0.        ],
        [  0.        ,   0.        ,   0.        ,   0.        ,
          63.66666667,   0.        ],
        [  0.        ,   0.        ,   0.        ,   0.        ,
           0.        ,  63.66666667]]),
 'hexagonal': array([[-21.66666667,   1.66666667,  -9.33333333,   0.        ,
           0.        ,   0.        ],
        [  1.66666667, -21.66666667,  -9.33333333,   0.        ,
           0.        ,   0.        ],
        [ -9.33333333,  -9.33333333,  77.33333333,   0.        ,
           0.        ,   0.        ],
        [  0.        ,   0.        ,   0.    

In [6]:
olivine['orthorhombic']

array([[ 16.,   0.,   2.,   0.,   0.,   0.],
       [  0., -16.,  -2.,   0.,   0.,   0.],
       [  2.,  -2.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,  -1.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   1.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.]])

In [7]:
olivine['tetragonal']

array([[ 3., -3.,  0.,  0.,  0.,  0.],
       [-3.,  3.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., -3.]])

In [8]:
np.around(olivine['hexagonal'], decimals=1)

array([[-21.7,   1.7,  -9.3,   0. ,   0. ,   0. ],
       [  1.7, -21.7,  -9.3,   0. ,   0. ,   0. ],
       [ -9.3,  -9.3,  77.3,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. ,  -2.7,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,  -2.7,   0. ],
       [  0. ,   0. ,   0. ,   0. ,   0. , -11.7]])

In [9]:
np.around(olivine['isotropic'], decimals=1)

array([[194.7,  67.3,  67.3,   0. ,   0. ,   0. ],
       [ 67.3, 194.7,  67.3,   0. ,   0. ,   0. ],
       [ 67.3,  67.3, 194.7,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. ,  63.7,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,  63.7,   0. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,  63.7]])

In [10]:
olivine['orthorhombic'] + olivine['tetragonal'] + np.around(olivine['hexagonal'], decimals=1) + np.around(olivine['isotropic'], decimals=1)

array([[192.,  66.,  60.,   0.,   0.,   0.],
       [ 66., 160.,  56.,   0.,   0.,   0.],
       [ 60.,  56., 272.,   0.,   0.,   0.],
       [  0.,   0.,   0.,  60.,   0.,   0.],
       [  0.,   0.,   0.,   0.,  62.,   0.],
       [  0.,   0.,   0.,   0.,   0.,  49.]])

In [11]:
(
np.linalg.norm(olivine['isotropic']),
np.linalg.norm(olivine['hexagonal']),
np.linalg.norm(olivine['tetragonal']),
np.linalg.norm(olivine['orthorhombic']),
np.linalg.norm(olivine['monoclinic']),
np.linalg.norm(Cij)
)


(391.2139227242984,
 86.1607025659997,
 6.708203932499361,
 23.021728866442675,
 0.0,
 410.4594986110079)

In [12]:
suma = (np.linalg.norm(olivine['isotropic']) +
        np.linalg.norm(olivine['hexagonal']) +
        np.linalg.norm(olivine['tetragonal']) +
        np.linalg.norm(olivine['orthorhombic']) +
        np.linalg.norm(olivine['monoclinic']))
suma

507.1045580892402

In [13]:
print(f" isotropic:   {100 * np.linalg.norm(olivine['isotropic']) / suma:.2f} %\n",
      f"hexagonal:   {100 * np.linalg.norm(olivine['hexagonal']) / suma:.2f} %\n",
      f"tetragonal:   {100 * np.linalg.norm(olivine['tetragonal']) / suma:.2f} %\n",
      f"orthorhombic: {100 * np.linalg.norm(olivine['orthorhombic']) / suma:.2f} %\n",
      f"monoclinic:   {100 * np.linalg.norm(olivine['monoclinic']) / suma:.2f} %")

 isotropic:   77.15 %
 hexagonal:   16.99 %
 tetragonal:   1.32 %
 orthorhombic: 4.54 %
 monoclinic:   0.00 %


In [14]:
# Elastic stiffness tensor of Enstatite used in Browaeys and Chevrot (2004)
Cij = np.array(
    [[255,  54,  72, 0.0, 0.0, 0.0],
    [  54, 214,  53, 0.0, 0.0, 0.0],
    [  72,  53, 178, 0.0, 0.0, 0.0],
    [ 0.0, 0.0, 0.0,  78, 0.0, 0.0],
    [ 0.0, 0.0, 0.0, 0.0,  82, 0.0],
    [ 0.0, 0.0, 0.0, 0.0, 0.0,  76]])

In [15]:
enstatite = decompose_Cij(Cij)

In [16]:
enstatite

{'isotropic': array([[216.2,  59.4,  59.4,   0. ,   0. ,   0. ],
        [ 59.4, 216.2,  59.4,   0. ,   0. ,   0. ],
        [ 59.4,  59.4, 216.2,   0. ,   0. ,   0. ],
        [  0. ,   0. ,   0. ,  78.4,   0. ,   0. ],
        [  0. ,   0. ,   0. ,   0. ,  78.4,   0. ],
        [  0. ,   0. ,   0. ,   0. ,   0. ,  78.4]]),
 'hexagonal': array([[ 11.175,   1.725,   3.1  ,   0.   ,   0.   ,   0.   ],
        [  1.725,  11.175,   3.1  ,   0.   ,   0.   ,   0.   ],
        [  3.1  ,   3.1  , -38.2  ,   0.   ,   0.   ,   0.   ],
        [  0.   ,   0.   ,   0.   ,   1.6  ,   0.   ,   0.   ],
        [  0.   ,   0.   ,   0.   ,   0.   ,   1.6  ,   0.   ],
        [  0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   4.725]]),
 'tetragonal': array([[ 7.125, -7.125,  0.   ,  0.   ,  0.   ,  0.   ],
        [-7.125,  7.125,  0.   ,  0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.   ,  0.

In [17]:
suma = (np.linalg.norm(enstatite['isotropic']) +
        np.linalg.norm(enstatite['hexagonal']) +
        np.linalg.norm(enstatite['tetragonal']) +
        np.linalg.norm(enstatite['orthorhombic']) +
        np.linalg.norm(enstatite['monoclinic']))
suma

516.9819451571002

In [18]:
print(f" isotropic:   {100 * np.linalg.norm(enstatite['isotropic']) / suma:.2f} %\n",
      f"hexagonal:    {100 * np.linalg.norm(enstatite['hexagonal']) / suma:.2f} %\n",
      f"tetragonal:   {100 * np.linalg.norm(enstatite['tetragonal']) / suma:.2f} %\n",
      f"orthorhombic: {100 * np.linalg.norm(enstatite['orthorhombic']) / suma:.2f} %\n",
      f"monoclinic:   {100 * np.linalg.norm(enstatite['monoclinic']) / suma:.2f} %")

 isotropic:   82.03 %
 hexagonal:    8.16 %
 tetragonal:   3.08 %
 orthorhombic: 6.73 %
 monoclinic:   0.00 %
