Any triclinic vector X in a given 3-D cartesian coordinate system can be decomposed by a cascade of projections into a sum of vectors belonging to the different symmetry classes: $X = X_{tric} + X_{mon} + X_{ort} + X_{tet} + X_{hex} + X_{iso}$.

In [1]:
import numpy as np
from decompose import *

In [2]:
# Elastic stiffness tensor of Olivine used in Browaeys and Chevrot (2004)
Cij = np.array(
    [[192,  66,  60, 0.0, 0.0, 0.0],
    [  66, 160,  56, 0.0, 0.0, 0.0],
    [  60,  56, 272, 0.0, 0.0, 0.0],
    [ 0.0, 0.0, 0.0,  60, 0.0, 0.0],
    [ 0.0, 0.0, 0.0, 0.0,  62, 0.0],
    [ 0.0, 0.0, 0.0, 0.0, 0.0,  49]])

In [3]:
olivine = decompose_Cij(Cij)

In [4]:
olivine

{'isotropic': array([[194.67,  67.33,  67.33,   0.  ,   0.  ,   0.  ],
        [ 67.33, 194.67,  67.33,   0.  ,   0.  ,   0.  ],
        [ 67.33,  67.33, 194.67,   0.  ,   0.  ,   0.  ],
        [  0.  ,   0.  ,   0.  ,  63.67,   0.  ,   0.  ],
        [  0.  ,   0.  ,   0.  ,   0.  ,  63.67,   0.  ],
        [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,  63.67]]),
 'hexagonal': array([[-21.67,   1.67,  -9.33,   0.  ,   0.  ,   0.  ],
        [  1.67, -21.67,  -9.33,   0.  ,   0.  ,   0.  ],
        [ -9.33,  -9.33,  77.33,   0.  ,   0.  ,   0.  ],
        [  0.  ,   0.  ,   0.  ,  -2.67,   0.  ,   0.  ],
        [  0.  ,   0.  ,   0.  ,   0.  ,  -2.67,   0.  ],
        [  0.  ,   0.  ,   0.  ,   0.  ,   0.  , -11.67]]),
 'tetragonal': array([[ 3., -3.,  0.,  0.,  0.,  0.],
        [-3.,  3.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0., -0.,  0.,  0.],
        [ 0.,  0.,  0.,  0., -0.,  0.],
        [ 0.,  0.,  0.,  0.,  0., -3.]]),
 'orthorhombic': a

In [5]:
olivine['orthorhombic']

array([[ 16.,   0.,   2.,   0.,   0.,   0.],
       [  0., -16.,  -2.,   0.,   0.,   0.],
       [  2.,  -2.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,  -1.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   1.,   0.],
       [  0.,   0.,   0.,   0.,   0.,  -0.]])

In [6]:
olivine['tetragonal']

array([[ 3., -3.,  0.,  0.,  0.,  0.],
       [-3.,  3.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., -3.]])

In [7]:
np.around(olivine['hexagonal'], decimals=1)

array([[-21.7,   1.7,  -9.3,   0. ,   0. ,   0. ],
       [  1.7, -21.7,  -9.3,   0. ,   0. ,   0. ],
       [ -9.3,  -9.3,  77.3,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. ,  -2.7,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,  -2.7,   0. ],
       [  0. ,   0. ,   0. ,   0. ,   0. , -11.7]])

In [8]:
np.around(olivine['isotropic'], decimals=1)

array([[194.7,  67.3,  67.3,   0. ,   0. ,   0. ],
       [ 67.3, 194.7,  67.3,   0. ,   0. ,   0. ],
       [ 67.3,  67.3, 194.7,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. ,  63.7,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,  63.7,   0. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,  63.7]])

In [9]:
olivine['orthorhombic'] + olivine['tetragonal'] + np.around(olivine['hexagonal'], decimals=1) + np.around(olivine['isotropic'], decimals=1)

array([[192.,  66.,  60.,   0.,   0.,   0.],
       [ 66., 160.,  56.,   0.,   0.,   0.],
       [ 60.,  56., 272.,   0.,   0.,   0.],
       [  0.,   0.,   0.,  60.,   0.,   0.],
       [  0.,   0.,   0.,   0.,  62.,   0.],
       [  0.,   0.,   0.,   0.,   0.,  49.]])

In [10]:
(
np.linalg.norm(tensor_to_vector(olivine['isotropic'])),
np.linalg.norm(tensor_to_vector(olivine['hexagonal'])),
np.linalg.norm(tensor_to_vector(olivine['tetragonal'])),
np.linalg.norm(tensor_to_vector(olivine['orthorhombic'])),
np.linalg.norm(tensor_to_vector(olivine['monoclinic'])),
np.linalg.norm(tensor_to_vector(olivine['triclinic'])),
np.linalg.norm(tensor_to_vector(Cij))
)


(435.356896006024,
 88.73931992076568,
 8.48528137423857,
 23.15167380558045,
 0.0,
 0.0,
 444.98539301869226)

In [11]:
suma = (np.linalg.norm(tensor_to_vector(olivine['isotropic'])) +
        np.linalg.norm(tensor_to_vector(olivine['hexagonal'])) +
        np.linalg.norm(tensor_to_vector(olivine['tetragonal'])) +
        np.linalg.norm(tensor_to_vector(olivine['orthorhombic'])) +
        np.linalg.norm(tensor_to_vector(olivine['monoclinic'])) +
        np.linalg.norm(tensor_to_vector(olivine['triclinic'])))
suma

555.7331711066087

In [12]:
print(f" isotropic:   {100 * np.linalg.norm(tensor_to_vector(olivine['isotropic'])) / suma:.2f} %\n",
      f"hexagonal:   {100 * np.linalg.norm(tensor_to_vector(olivine['hexagonal'])) / suma:.2f} %\n",
      f"tetragonal:   {100 * np.linalg.norm(tensor_to_vector(olivine['tetragonal'])) / suma:.2f} %\n",
      f"orthorhombic: {100 * np.linalg.norm(tensor_to_vector(olivine['orthorhombic'])) / suma:.2f} %\n",
      f"monoclinic: {100 * np.linalg.norm(tensor_to_vector(olivine['monoclinic'])) / suma:.2f} %\n",
      f"triclinic:   {100 * np.linalg.norm(tensor_to_vector(olivine['triclinic'])) / suma:.2f} %")

 isotropic:   78.34 %
 hexagonal:   15.97 %
 tetragonal:   1.53 %
 orthorhombic: 4.17 %
 monoclinic: 0.00 %
 triclinic:   0.00 %


In [13]:
calc_percentages(olivine)

{'isotropic': 78.33919561416779,
 'anisotropic': 21.660804385832208,
 'hexagonal': 15.967972497316062,
 'tetragonal': 1.5268624972200555,
 'orthorhombic': 4.165969391296091,
 'monoclinic': 0.0,
 'triclinic': 0.0}

In [14]:
# Elastic stiffness tensor of Enstatite used in Browaeys and Chevrot (2004)
Cij = np.array(
    [[255,  54,  72, 0.0, 0.0, 0.0],
    [  54, 214,  53, 0.0, 0.0, 0.0],
    [  72,  53, 178, 0.0, 0.0, 0.0],
    [ 0.0, 0.0, 0.0,  78, 0.0, 0.0],
    [ 0.0, 0.0, 0.0, 0.0,  82, 0.0],
    [ 0.0, 0.0, 0.0, 0.0, 0.0,  76]])

In [15]:
enstatite = decompose_Cij(Cij)

In [16]:
enstatite

{'isotropic': array([[216.2,  59.4,  59.4,   0. ,   0. ,   0. ],
        [ 59.4, 216.2,  59.4,   0. ,   0. ,   0. ],
        [ 59.4,  59.4, 216.2,   0. ,   0. ,   0. ],
        [  0. ,   0. ,   0. ,  78.4,   0. ,   0. ],
        [  0. ,   0. ,   0. ,   0. ,  78.4,   0. ],
        [  0. ,   0. ,   0. ,   0. ,   0. ,  78.4]]),
 'hexagonal': array([[ 11.18,   1.73,   3.1 ,   0.  ,   0.  ,   0.  ],
        [  1.73,  11.18,   3.1 ,   0.  ,   0.  ,   0.  ],
        [  3.1 ,   3.1 , -38.2 ,   0.  ,   0.  ,   0.  ],
        [  0.  ,   0.  ,   0.  ,   1.6 ,   0.  ,   0.  ],
        [  0.  ,   0.  ,   0.  ,   0.  ,   1.6 ,   0.  ],
        [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   4.72]]),
 'tetragonal': array([[ 7.12, -7.13,  0.  ,  0.  ,  0.  ,  0.  ],
        [-7.13,  7.12,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  , -0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  , -0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ,

In [17]:
suma2 = (np.linalg.norm(enstatite['isotropic']) +
        np.linalg.norm(enstatite['hexagonal']) +
        np.linalg.norm(enstatite['tetragonal']) +
        np.linalg.norm(enstatite['orthorhombic']) +
        np.linalg.norm(enstatite['monoclinic']))
suma1 = (np.linalg.norm(tensor_to_vector(enstatite['isotropic'])) +
        np.linalg.norm(tensor_to_vector(enstatite['hexagonal'])) +
        np.linalg.norm(tensor_to_vector(enstatite['tetragonal'])) +
        np.linalg.norm(tensor_to_vector(enstatite['orthorhombic'])) +
        np.linalg.norm(tensor_to_vector(enstatite['monoclinic'])))

In [18]:
print(f" isotropic:   {100 * np.linalg.norm(tensor_to_vector(enstatite['isotropic'])) / suma1:.2f} %\n",
      f"hexagonal:    {100 * np.linalg.norm(tensor_to_vector(enstatite['hexagonal'])) / suma1:.2f} %\n",
      f"tetragonal:   {100 * np.linalg.norm(tensor_to_vector(enstatite['tetragonal'])) / suma1:.2f} %\n",
      f"orthorhombic: {100 * np.linalg.norm(tensor_to_vector(enstatite['orthorhombic'])) / suma1:.2f} %\n",
      f"monoclinic:   {100 * np.linalg.norm(tensor_to_vector(enstatite['monoclinic'])) / suma1:.2f} %")

 isotropic:   83.13 %
 hexagonal:    7.40 %
 tetragonal:   3.45 %
 orthorhombic: 6.02 %
 monoclinic:   0.00 %


In [19]:
# test calc_percentages()
calc_percentages(enstatite)

{'isotropic': 83.12674406582346,
 'anisotropic': 16.87325593417654,
 'hexagonal': 7.399415968128989,
 'tetragonal': 3.4533459320829607,
 'orthorhombic': 6.0204940339645985,
 'monoclinic': 0.0,
 'triclinic': 0.0}

In [20]:
print(f" isotropic:   {100 * np.linalg.norm(enstatite['isotropic']) / suma2:.2f} %\n",
      f"hexagonal:    {100 * np.linalg.norm(enstatite['hexagonal']) / suma2:.2f} %\n",
      f"tetragonal:   {100 * np.linalg.norm(enstatite['tetragonal']) / suma2:.2f} %\n",
      f"orthorhombic: {100 * np.linalg.norm(enstatite['orthorhombic']) / suma2:.2f} %\n",
      f"monoclinic:   {100 * np.linalg.norm(enstatite['monoclinic']) / suma2:.2f} %")

 isotropic:   82.03 %
 hexagonal:    8.16 %
 tetragonal:   3.08 %
 orthorhombic: 6.73 %
 monoclinic:   0.00 %


In [21]:
calc_percentages(enstatite)

{'isotropic': 83.12674406582346,
 'anisotropic': 16.87325593417654,
 'hexagonal': 7.399415968128989,
 'tetragonal': 3.4533459320829607,
 'orthorhombic': 6.0204940339645985,
 'monoclinic': 0.0,
 'triclinic': 0.0}

# Test orthogonal_projector

In [22]:
orthogonal_projector('tetragonal')[0:9, 0:9]

array([[0.5, 0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.5, 0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 1. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.5, 0.5, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.5, 0.5, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 1. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0.5, 0.5, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0.5, 0.5, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 1. ]])

In [23]:
np.around(orthogonal_projector('hexagonal')[0:9, 0:9], decimals=2)

array([[ 0.38,  0.38,  0.  ,  0.  ,  0.  ,  0.18,  0.  ,  0.  ,  0.25],
       [ 0.38,  0.38,  0.  ,  0.  ,  0.  ,  0.18,  0.  ,  0.  ,  0.25],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.5 ,  0.5 ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.5 ,  0.5 ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.18,  0.18,  0.  ,  0.  ,  0.  ,  0.75,  0.  ,  0.  , -0.35],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.5 ,  0.5 ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.5 ,  0.5 ,  0.  ],
       [ 0.25,  0.25,  0.  ,  0.  ,  0.  , -0.35,  0.  ,  0.  ,  0.5 ]])

In [24]:
np.around(orthogonal_projector('isotropic')[0:9, 0:9], decimals=2)

array([[ 0.2 ,  0.2 ,  0.2 ,  0.09,  0.09,  0.09,  0.13,  0.13,  0.13],
       [ 0.2 ,  0.2 ,  0.2 ,  0.09,  0.09,  0.09,  0.13,  0.13,  0.13],
       [ 0.2 ,  0.2 ,  0.2 ,  0.09,  0.09,  0.09,  0.13,  0.13,  0.13],
       [ 0.09,  0.09,  0.09,  0.27,  0.27,  0.27, -0.09, -0.09, -0.09],
       [ 0.09,  0.09,  0.09,  0.27,  0.27,  0.27, -0.09, -0.09, -0.09],
       [ 0.09,  0.09,  0.09,  0.27,  0.27,  0.27, -0.09, -0.09, -0.09],
       [ 0.13,  0.13,  0.13, -0.09, -0.09, -0.09,  0.2 ,  0.2 ,  0.2 ],
       [ 0.13,  0.13,  0.13, -0.09, -0.09, -0.09,  0.2 ,  0.2 ,  0.2 ],
       [ 0.13,  0.13,  0.13, -0.09, -0.09, -0.09,  0.2 ,  0.2 ,  0.2 ]])

In [25]:
np.around(orthogonal_projector('orthorhombic')[0:16, 0:16], decimals=2)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [26]:
np.around(orthogonal_projector('monoclinic')[0:16, 0:16], decimals=1)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [27]:
np.around(orthogonal_projector('monoclinic')[15:, 15:], decimals=1)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [28]:
np.around(orthogonal_projector('triclinic'), decimals=1)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.,